kubernetes:
  excluded_namespaces:
    - argocd
  included_namespaces:
    - default

external_services:
  aws_secrets_manager:
    enabled: true
    accounts:
      - "12345678910"
    regions:
      - "eu-west-1"
  aws_parameter_store:
    enabled: true
    accounts:
      - "12345678910"
    regions:
      - "eu-west-1"
